//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoogleMap.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Country
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Country()
        {
            this.Cities = new HashSet<City>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string Name_en { get; set; }
        public string Currency { get; set; }
        public string CurrencyName { get; set; }
        public double Log { get; set; }
        public double Lat { get; set; }
        public string Police_Number { get; set; }
        public string Ambulance_Number { get; set; }
        public string Fire_Number { get; set; }
        public string History { get; set; }
        public string History_en { get; set; }
        public string Roles { get; set; }
        public string Roles_en { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<City> Cities { get; set; }
    }
}
